authentication:
  user: karamj@jfrog.com
  password: hahahaha
  url: pe16366karamj.jfrog.io

artifactory:
  new_repositories:
    - repo1:
        key: pypi-local-test
        packageType: pypi
        rclass: local
    - repo2:
        key: docker-local-test
        packageType: docker
        rclass: local

xray:
  policies:
    - policy1:
        name: karam_policy
        description: This is a security policy
        type: security
        rules:
          - name: sec_rule
            criteria:
              min_severity: medium
            actions:
              block_download:
                active: true
                unscanned: true
              block_release_bundle_distribution: true
              fail_build: true
              notify_deployer: true
              notify_watch_recipients: true
            priority: 1
    - policy2:
        name: DockerSecurityPolicy
        type: security
        description: "Security policy for all docker images"
        rules:
          name: securityRule
          priority: 1
          criteria:
            min_severity: High

  watches:
    - watch1:
        general_data:
          name: vuln-prod
          description: This is a new watch created using API V2
          active: true
        project_resources:
          resources:
            - type: repository
              bin_mgr_id: art-prod-eu
              name: docker-local-test
              filters:
                - type: regex
                  value: ".*"
        assigned_policies:
          - name: karam_policy
            type: security
    - watch2 :
        general_data:
          name: all-repositories
          description: This is a new watch created using API V2
          active: true
        project_resources:
          resources:
            - type: all-repos
              filters:
                - type: package-type
                  value: Docker
                - type: package-type
                  value: Debian
        assigned_policies:
          - name: karam_policy
            type: security

pipeline:
  source:
    projectId: 1
    projectIntegrationId:
    repositoryFullName: "myrepo/docker-sample"
    branch: master
    fileFilter: pipelines.yml

  integrations:
    - Name: MyGithub
      projectId: 1
      masterIntegrationId: 20
      masterIntegrationName: github
      formJSONValues:
        - label: gittoken
          value: ''
        - label: url
          value: "https://api.github.com"
      permissions:
        pipelineSources:
          allowAllPipelineSources: true

    - Name: MyArtifactory
      projectId: 1
      masterIntegrationId: 98
      masterIntegrationName: artifactory
      formJSONValues:
        - label: apikey
          value: ''
        - label: url
          value: '--insert--'
        - label: user
          value: '--insert--'
      permissions:
        pipelineSources:
          allowAllPipelineSources: true
          